# # Copyright (C) 2022 Intel Corporation
# # SPDX-License-Identifier: MIT License

model:
  class_path: S2EFPointCloudModule
  init_args:
    gnn:
      class_path: ocpmodels.models.GalaPotential
      init_args:
        # Node Embedding
        D_in: 200
        hidden_dim: 128
#        depth: 4
#        dilation: 2
#        residual: True
#        nonlinearities: True
        merge_fun: concat
        join_fun: concat
        invariant_mode: full
        covariant_mode: full
        include_normalized_products: True
#        rank: 2
        invar_value_normalization: momentum
        eqvar_value_normalization: momentum_layer
        value_normalization: layer
        score_normalization: layer
        block_normalization: layer
        equivariant_attention: False
        tied_attention: True
#        pc_mini_batch: 8
#        pc_size: 30
    regress_forces: True
    normalize_kwargs:
      target_mean: -0.7554450631141663
      target_std: 2.887317180633545
      grad_target_mean: 0.0
      grad_target_std: 2.887317180633545
    lr: 0.001
    gamma: 0.8
    nan_check: True
