# Copyright (C) 2022 Intel Corporation
# SPDX-License-Identifier: MIT License

trainer:
  accelerator: "gpu"
  # min_epochs: 30
  # max_epochs: 300
  max_steps: 5
  devices: 8
  strategy: ddp
  accumulate_grad_batches: 64
  log_every_n_steps: 100
  logger:
    - class_path: pytorch_lightning.loggers.CSVLogger
      init_args:
        save_dir: "matsciml-logs"
        name: "training-logs"
#seed_everything: 6
