name: Build env
on:
  workflow_dispatch:
  workflow_call:
jobs:
  mamba-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create micromamba env
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.7-0'
          environment-file: conda.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
