name: Run PyTorch Lightning related PyTests
env:
  COLUMNS: 120
on:
  pull_request:
    paths:
      - 'matsciml/lightning/**'
  workflow_dispatch:
jobs:
  lightning-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create micromamba env
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.7-0'
          environment-file: conda.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
          generate-run-shell: true
      - name: Install current matsciml
        run: |
          pip install .
        shell: micromamba-shell {0}
      - name: Install PyTest
        run: |
          pip install pytest pytest-dependency pytest-pretty
        shell: micromamba-shell {0}
      - name: Print out environment
        run: |
          micromamba env export && pip freeze
        shell: micromamba-shell {0}
      - name: Run pytest in lightning submodule
        run: |
          pytest -v -m "not lmdb and not slow and not remote_request" ./matsciml/lightning
        shell: micromamba-shell {0}
